
# This can be used to run a production version of the Angular and Node containers
# See the readme.md for details on changes that are required in the Angular service

# Run docker-compose -f docker-compose.prod.yml build
# Run docker-compose -f docker-compose.prod.yml up
# Live long and prosper

version: '3.1'

services:

  nginx:
    container_name: nginx-vue
    image: nginx-vue
    build:
      context: .
      dockerfile: nginx.prod.dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - node
    networks:
      - app-network

  node:
    container_name: vue-node-service
    image: vue-node-service
    build:
      context: ./server
      dockerfile: node.dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge